services:
  postgres:
    image: postgres:15-alpine
    container_name: clowie_db
    environment:
      POSTGRES_USER: clowie_admin
      POSTGRES_PASSWORD: clowie_password
      POSTGRES_DB: clowie_db
    ports:
      - "5432:5432"
    volumes:
      # This ensures your data isn't deleted if the container stops
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: